import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  injectMarkdown,
  injectPlaintext,
  removeMarkdown,
  removePlaintext,
} from "../../src/integrations/shared.js";
import { writeFileSync, readFileSync, unlinkSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

describe("Integration shared functions", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = join(tmpdir(), `integration-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
    mkdirSync(tempDir, { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(tempDir, { recursive: true, force: true });
    } catch { /* ignore */ }
  });

  describe("injectMarkdown", () => {
    it("injects markdown block into new file", () => {
      const file = "CLAUDE.md";
      injectMarkdown(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("<!-- codebase:start -->");
      expect(content).toContain("<!-- codebase:end -->");
      expect(content).toContain("## Project Context (auto-generated by codebase)");
      expect(content).toContain("npx codebase brief");
    });

    it("injects markdown block into existing file", () => {
      const file = "CLAUDE.md";
      writeFileSync(join(tempDir, file), "# Existing content\n\nSome text here.\n", "utf-8");

      injectMarkdown(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("# Existing content");
      expect(content).toContain("<!-- codebase:start -->");
      expect(content).toContain("Some text here.");
      // Verify the marker appears after the existing content
      const existingIdx = content.indexOf("Existing content");
      const markerIdx = content.indexOf("<!-- codebase:start -->");
      expect(markerIdx).toBeGreaterThan(existingIdx);
    });

    it("replaces existing markdown block", () => {
      const file = "CLAUDE.md";
      writeFileSync(
        join(tempDir, file),
        "# Rules\n\n<!-- codebase:start -->\nOld content\n<!-- codebase:end -->\n",
        "utf-8"
      );

      injectMarkdown(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("<!-- codebase:start -->");
      expect(content).toContain("<!-- codebase:end -->");
      expect(content).not.toContain("Old content");
      expect(content).toContain("npx codebase brief");
    });

    it("preserves content before existing block", () => {
      const file = "CLAUDE.md";
      const existingContent = "# Project Rules\n\nBe nice.\n";
      writeFileSync(
        join(tempDir, file),
        existingContent + "<!-- codebase:start -->\nold\n<!-- codebase:end -->\n",
        "utf-8"
      );

      injectMarkdown(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("# Project Rules");
      expect(content).toContain("Be nice.");
    });

    it("handles missing end marker", () => {
      const file = "CLAUDE.md";
      const existingContent = "# Rules\n\n<!-- codebase:start -->\nNo end marker";
      writeFileSync(join(tempDir, file), existingContent, "utf-8");

      injectMarkdown(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("<!-- codebase:start -->");
      expect(content).toContain("<!-- codebase:end -->");
    });
  });

  describe("injectPlaintext", () => {
    it("injects plaintext block into new file", () => {
      const file = ".cursorrules";
      injectPlaintext(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("# codebase:start");
      expect(content).toContain("# codebase:end");
      expect(content).toContain("# Project Context (auto-generated by codebase)");
      expect(content).toContain("npx codebase brief");
    });

    it("injects plaintext block into existing file", () => {
      const file = ".cursorrules";
      writeFileSync(join(tempDir, file), "Existing rules\n", "utf-8");

      injectPlaintext(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("Existing rules");
      expect(content).toContain("# codebase:start");
      expect(content).toContain("# codebase:end");
    });

    it("replaces existing plaintext block", () => {
      const file = ".cursorrules";
      writeFileSync(
        join(tempDir, file),
        "Rules\n# codebase:start\nOld content\n# codebase:end\n",
        "utf-8"
      );

      injectPlaintext(tempDir, file);

      const content = readFileSync(join(tempDir, file), "utf-8");
      expect(content).toContain("# codebase:start");
      expect(content).toContain("# codebase:end");
      expect(content).not.toContain("Old content");
      expect(content).toContain("npx codebase brief");
    });
  });

  describe("removeMarkdown", () => {
    it("removes markdown block from file", () => {
      const file = "CLAUDE.md";
      const content = "# Rules\n\n<!-- codebase:start -->\nInjected content\n<!-- codebase:end -->\n## More rules\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removeMarkdown(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toContain("# Rules");
      expect(result).toContain("## More rules");
      expect(result).not.toContain("<!-- codebase:start -->");
      expect(result).not.toContain("Injected content");
      expect(result).not.toContain("<!-- codebase:end -->");
    });

    it("does nothing when file doesn't exist", () => {
      const file = "nonexistent.md";
      expect(() => removeMarkdown(tempDir, file)).not.toThrow();
    });

    it("does nothing when no markers present", () => {
      const file = "CLAUDE.md";
      const content = "# Rules\n\nSome content\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removeMarkdown(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toBe(content);
    });

    it("handles missing start marker", () => {
      const file = "CLAUDE.md";
      const content = "# Rules\n\nContent\n<!-- codebase:end -->\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removeMarkdown(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toContain("Content");
    });

    it("handles missing end marker (does nothing if only start marker)", () => {
      const file = "missing-end.md"; // Use a different filename to avoid conflicts
      const content = "# Rules\n<!-- codebase:start -->\nContent\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removeMarkdown(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      // Function requires both markers to remove content, so it should be unchanged
      expect(result).toContain("<!-- codebase:start -->");
      expect(result).toContain("# Rules");
      expect(result).toContain("Content");
    });
  });

  describe("removePlaintext", () => {
    it("removes plaintext block from file", () => {
      const file = ".cursorrules";
      const content = "Rules\n# codebase:start\nInjected\n# codebase:end\nMore rules\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removePlaintext(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toContain("Rules");
      expect(result).toContain("More rules");
      expect(result).not.toContain("# codebase:start");
      expect(result).not.toContain("Injected");
      expect(result).not.toContain("# codebase:end");
    });

    it("does nothing when file doesn't exist", () => {
      const file = "nonexistent.txt";
      expect(() => removePlaintext(tempDir, file)).not.toThrow();
    });

    it("does nothing when no markers present", () => {
      const file = ".cursorrules";
      const content = "Just rules\n";
      writeFileSync(join(tempDir, file), content, "utf-8");

      removePlaintext(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toBe(content);
    });
  });

  describe("combined injection and removal", () => {
    it("can inject then remove markdown", () => {
      const file = "CLAUDE.md";
      const originalContent = "# Original Rules\n";

      writeFileSync(join(tempDir, file), originalContent, "utf-8");
      injectMarkdown(tempDir, file);
      removeMarkdown(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toContain("# Original Rules");
      expect(result).not.toContain("<!-- codebase:start -->");
    });

    it("can inject then remove plaintext", () => {
      const file = ".cursorrules";
      const originalContent = "Original rules\n";

      writeFileSync(join(tempDir, file), originalContent, "utf-8");
      injectPlaintext(tempDir, file);
      removePlaintext(tempDir, file);

      const result = readFileSync(join(tempDir, file), "utf-8");
      expect(result).toContain("Original rules");
      expect(result).not.toContain("# codebase:start");
    });
  });
});
