import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const START_MARKER = "<!-- codebase:start -->";
const END_MARKER = "<!-- codebase:end -->";

const HASH_START_MARKER = "# codebase:start";
const HASH_END_MARKER = "# codebase:end";

const INJECT_BLOCK_MD = `
${START_MARKER}
## Project Context (auto-generated by codebase)

**This project uses \`codebase\` for AI context. Run commands below instead of exploring files.**

### Session Start
\`\`\`
npx codebase brief
\`\`\`
Returns: project identity, tech stack, commands, structure, current status, next task, blockers, decisions — everything you need in one call.

### Commands (your interface — use these, don't read files)
| Command | What it returns |
|---|---|
| \`npx codebase brief\` | Full project briefing — **run this first** |
| \`npx codebase next\` | Highest-priority task + what's in progress |
| \`npx codebase status\` | Kanban board, priorities, milestones |
| \`npx codebase query <path>\` | Any data point (e.g. \`stack.languages\`, \`commands.test\`) |
| \`npx codebase issue create "title"\` | Track a bug, feature, or TODO |
| \`npx codebase issue close <n> --reason "why"\` | Close an issue after fixing it |

### Rules
- **Never explore the codebase to discover stack/commands/structure** — it's already in \`brief\`
- **Check \`next\` before starting work** — don't duplicate in-progress tasks
- **Create issues for bugs/TODOs you find** — keep the project brain alive
- **Close issues when you fix them** — with a reason so the team knows why
${END_MARKER}`;

const INJECT_BLOCK_PLAIN = `
${HASH_START_MARKER}
# Project Context (auto-generated by codebase)
#
# This project uses \`codebase\` for AI context. Run commands instead of exploring files.
#
# SESSION START: npx codebase brief
#   → Returns project identity, stack, commands, status, next task, blockers, decisions
#
# COMMANDS (your interface):
#   npx codebase brief                           → Full project briefing (run first)
#   npx codebase next                            → Highest-priority task + in-progress
#   npx codebase status                          → Kanban, priorities, milestones
#   npx codebase query <path>                    → Any data (e.g. stack.languages)
#   npx codebase issue create "title"            → Track bugs/features/TODOs
#   npx codebase issue close <n> --reason "why"  → Close after fixing
#
# RULES:
#   - Never explore codebase to discover stack/commands — it's in brief
#   - Check next before starting work — don't duplicate in-progress tasks
#   - Create issues for bugs/TODOs — keep the project brain alive
#   - Close issues when fixed — with a reason
${HASH_END_MARKER}`;

export function fileExistsAt(root: string, file: string): boolean {
  return existsSync(join(root, file));
}

export function injectMarkdown(root: string, file: string): void {
  const path = join(root, file);
  let content = existsSync(path) ? readFileSync(path, "utf-8") : "";

  if (content.includes(START_MARKER)) {
    // Already injected — replace with updated version
    const startIdx = content.indexOf(START_MARKER);
    const endIdx = content.indexOf(END_MARKER);
    if (startIdx !== -1 && endIdx !== -1) {
      content = content.slice(0, startIdx) + content.slice(endIdx + END_MARKER.length);
      content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
    }
  }

  writeFileSync(path, content.trimEnd() + "\n" + INJECT_BLOCK_MD + "\n", "utf-8");
}

export function injectPlaintext(root: string, file: string): void {
  const path = join(root, file);
  let content = existsSync(path) ? readFileSync(path, "utf-8") : "";

  if (content.includes(HASH_START_MARKER)) {
    // Already injected — replace with updated version
    const startIdx = content.indexOf(HASH_START_MARKER);
    const endIdx = content.indexOf(HASH_END_MARKER);
    if (startIdx !== -1 && endIdx !== -1) {
      content = content.slice(0, startIdx) + content.slice(endIdx + HASH_END_MARKER.length);
      content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
    }
  }

  writeFileSync(path, content.trimEnd() + "\n" + INJECT_BLOCK_PLAIN + "\n", "utf-8");
}

export function removeMarkdown(root: string, file: string): void {
  const path = join(root, file);
  if (!existsSync(path)) return;

  let content = readFileSync(path, "utf-8");
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + content.slice(endIdx + END_MARKER.length);
    content = content.replace(/\n{3,}/g, "\n\n").trim() + "\n";
    writeFileSync(path, content, "utf-8");
  }
}

export function removePlaintext(root: string, file: string): void {
  const path = join(root, file);
  if (!existsSync(path)) return;

  let content = readFileSync(path, "utf-8");
  const startIdx = content.indexOf(HASH_START_MARKER);
  const endIdx = content.indexOf(HASH_END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + content.slice(endIdx + HASH_END_MARKER.length);
    content = content.replace(/\n{3,}/g, "\n\n").trim() + "\n";
    writeFileSync(path, content, "utf-8");
  }
}
