import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Manifest } from "../types.js";

const START_MARKER = "<!-- codebase:start -->";
const END_MARKER = "<!-- codebase:end -->";

const HASH_START_MARKER = "# codebase:start";
const HASH_END_MARKER = "# codebase:end";

const INJECT_BLOCK_MD = `
${START_MARKER}
## Project Context (auto-generated by codebase)

**This project uses \`codebase\` for AI context. Run commands below instead of exploring files.**

### Session Start
\`\`\`
npx codebase brief
\`\`\`
Returns: project identity, tech stack, commands, structure, current status, next task, blockers, decisions — everything you need in one call.

### Commands (your interface — use these, don't read files)
| Command | What it returns |
|---|---|
| \`npx codebase brief\` | Full project briefing — **run this first** |
| \`npx codebase next\` | Highest-priority task + what's in progress |
| \`npx codebase status\` | Kanban board, priorities, milestones |
| \`npx codebase query <path>\` | Any data point (e.g. \`stack.languages\`, \`commands.test\`) |
| \`npx codebase issue create "title"\` | Track a bug, feature, or TODO |
| \`npx codebase issue close <n> --reason "why"\` | Close an issue after fixing it |

### Rules
- **Never explore the codebase to discover stack/commands/structure** — it's already in \`brief\`
- **Check \`next\` before starting work** — don't duplicate in-progress tasks
- **Create issues for bugs/TODOs you find** — keep the project brain alive
- **Close issues when you fix them** — with a reason so the team knows why

### Vibekit Workflow
\`\`\`
/simulate → /build → /launch
\`\`\`
- \`/simulate\` — Playwright customer journeys find & fix bugs inline. Creates GitHub issues for arch problems.
- \`/build\` — Implements architectural issues autonomously. Runs until all \`arch\`+\`vibekit\` issues are closed.
- \`/launch\` — Gates on open bugs, generates GTM artifacts, creates GitHub release, merges to main.

### Browser Automation (agent-browser)
Commands: \`open <url>\`, \`snapshot -i\` (→ \`@e1\`/\`@e2\` refs), \`click @e1\`, \`fill @e2 "text"\`, \`screenshot\`, \`auth save/login <profile>\`, \`state save/load <name>\`.
${END_MARKER}`;

const INJECT_BLOCK_PLAIN = `
${HASH_START_MARKER}
# Project Context (auto-generated by codebase)
#
# This project uses \`codebase\` for AI context. Run commands instead of exploring files.
#
# SESSION START: npx codebase brief
#   → Returns project identity, stack, commands, status, next task, blockers, decisions
#
# COMMANDS (your interface):
#   npx codebase brief                           → Full project briefing (run first)
#   npx codebase next                            → Highest-priority task + in-progress
#   npx codebase status                          → Kanban, priorities, milestones
#   npx codebase query <path>                    → Any data (e.g. stack.languages)
#   npx codebase issue create "title"            → Track bugs/features/TODOs
#   npx codebase issue close <n> --reason "why"  → Close after fixing
#
# RULES:
#   - Never explore codebase to discover stack/commands — it's in brief
#   - Check next before starting work — don't duplicate in-progress tasks
#   - Create issues for bugs/TODOs — keep the project brain alive
#   - Close issues when fixed — with a reason
${HASH_END_MARKER}`;

interface ManifestSummary {
  name: string;
  description: string | null;
  languages: string[];
  frameworks: string[];
  commands: Record<string, string | null>;
}

function readManifestSummary(root: string): ManifestSummary | null {
  try {
    const raw = readFileSync(join(root, ".codebase.json"), "utf-8");
    const m = JSON.parse(raw) as Manifest;
    return {
      name: m.project?.name || "Unknown",
      description: m.project?.description || null,
      languages: m.stack?.languages || [],
      frameworks: m.stack?.frameworks || [],
      commands: m.commands || {},
    };
  } catch {
    return null;
  }
}

function buildDynamicBlockMd(root: string): string {
  const summary = readManifestSummary(root);
  if (!summary) {
    return INJECT_BLOCK_MD;
  }

  const stackParts = [...summary.languages, ...summary.frameworks].filter(Boolean);
  const stack = stackParts.length ? stackParts.join(", ") : "unknown";

  const cmdEntries = Object.entries(summary.commands).filter(([, v]) => v);
  const cmdLines = cmdEntries.map(([k, v]) => `| \`${k}\` | \`${v}\` |`).join("\n");
  const cmdTable = cmdLines
    ? `\n### Project Commands\n| Task | Command |\n|---|---|\n${cmdLines}\n`
    : "";

  return `
${START_MARKER}
## Project Context (auto-generated by codebase)

**${summary.name}**${summary.description ? ` — ${summary.description}` : ""}
**Stack:** ${stack}
${cmdTable}
**This project uses \`codebase\` for AI context. Run commands below instead of exploring files.**

### Session Start
\`\`\`
npx codebase brief
\`\`\`
Returns: project identity, tech stack, commands, structure, current status, next task, blockers, decisions — everything you need in one call.

### Commands (your interface — use these, don't read files)
| Command | What it returns |
|---|---|
| \`npx codebase brief\` | Full project briefing — **run this first** |
| \`npx codebase next\` | Highest-priority task + what's in progress |
| \`npx codebase status\` | Kanban board, priorities, milestones |
| \`npx codebase query <path>\` | Any data point (e.g. \`stack.languages\`, \`commands.test\`) |
| \`npx codebase issue create "title"\` | Track a bug, feature, or TODO |
| \`npx codebase issue close <n> --reason "why"\` | Close an issue after fixing it |

### Rules
- **Never explore the codebase to discover stack/commands/structure** — it's already in \`brief\`
- **Check \`next\` before starting work** — don't duplicate in-progress tasks
- **Create issues for bugs/TODOs you find** — keep the project brain alive
- **Close issues when you fix them** — with a reason so the team knows why

### Vibekit Workflow
\`\`\`
/simulate → /build → /launch
\`\`\`
- \`/simulate\` — Playwright customer journeys find & fix bugs inline. Creates GitHub issues for arch problems.
- \`/build\` — Implements architectural issues autonomously. Runs until all \`arch\`+\`vibekit\` issues are closed.
- \`/launch\` — Gates on open bugs, generates GTM artifacts, creates GitHub release, merges to main.

### Browser Automation (agent-browser)
Commands: \`open <url>\`, \`snapshot -i\` (→ \`@e1\`/\`@e2\` refs), \`click @e1\`, \`fill @e2 "text"\`, \`screenshot\`, \`auth save/login <profile>\`, \`state save/load <name>\`.
${END_MARKER}`;
}

function buildDynamicBlockPlain(root: string): string {
  const summary = readManifestSummary(root);
  if (!summary) {
    return INJECT_BLOCK_PLAIN;
  }

  const stackParts = [...summary.languages, ...summary.frameworks].filter(Boolean);
  const stack = stackParts.length ? stackParts.join(", ") : "unknown";

  const cmdEntries = Object.entries(summary.commands).filter(([, v]) => v);
  const cmdLines = cmdEntries.map(([k, v]) => `#   ${k}: ${v}`).join("\n");
  const cmdSection = cmdLines ? `#\n# PROJECT COMMANDS:\n${cmdLines}\n` : "";

  return `
${HASH_START_MARKER}
# Project Context (auto-generated by codebase)
#
# ${summary.name}${summary.description ? ` — ${summary.description}` : ""}
# Stack: ${stack}
${cmdSection}#
# This project uses \`codebase\` for AI context. Run commands instead of exploring files.
#
# SESSION START: npx codebase brief
#   → Returns project identity, stack, commands, status, next task, blockers, decisions
#
# COMMANDS (your interface):
#   npx codebase brief                           → Full project briefing (run first)
#   npx codebase next                            → Highest-priority task + in-progress
#   npx codebase status                          → Kanban, priorities, milestones
#   npx codebase query <path>                    → Any data (e.g. stack.languages)
#   npx codebase issue create "title"            → Track bugs/features/TODOs
#   npx codebase issue close <n> --reason "why"  → Close after fixing
#
# RULES:
#   - Never explore codebase to discover stack/commands — it's in brief
#   - Check next before starting work — don't duplicate in-progress tasks
#   - Create issues for bugs/TODOs — keep the project brain alive
#   - Close issues when fixed — with a reason
${HASH_END_MARKER}`;
}

export function fileExistsAt(root: string, file: string): boolean {
  return existsSync(join(root, file));
}

export function injectMarkdown(root: string, file: string): void {
  const path = join(root, file);
  let content = existsSync(path) ? readFileSync(path, "utf-8") : "";

  if (content.includes(START_MARKER)) {
    // Already injected — replace with updated version
    const startIdx = content.indexOf(START_MARKER);
    const endIdx = content.indexOf(END_MARKER);
    if (startIdx !== -1 && endIdx !== -1) {
      content = content.slice(0, startIdx) + content.slice(endIdx + END_MARKER.length);
      content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
    }
  }

  writeFileSync(path, content.trimEnd() + "\n" + buildDynamicBlockMd(root) + "\n", "utf-8");
}

export function injectPlaintext(root: string, file: string): void {
  const path = join(root, file);
  let content = existsSync(path) ? readFileSync(path, "utf-8") : "";

  if (content.includes(HASH_START_MARKER)) {
    // Already injected — replace with updated version
    const startIdx = content.indexOf(HASH_START_MARKER);
    const endIdx = content.indexOf(HASH_END_MARKER);
    if (startIdx !== -1 && endIdx !== -1) {
      content = content.slice(0, startIdx) + content.slice(endIdx + HASH_END_MARKER.length);
      content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
    }
  }

  writeFileSync(path, content.trimEnd() + "\n" + buildDynamicBlockPlain(root) + "\n", "utf-8");
}

export function removeMarkdown(root: string, file: string): void {
  const path = join(root, file);
  if (!existsSync(path)) {
    return;
  }

  let content = readFileSync(path, "utf-8");
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  // Only remove if both markers are present
  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + content.slice(endIdx + END_MARKER.length);
    content = content.replace(/\n{3,}/g, "\n\n").trim() + "\n";
    writeFileSync(path, content, "utf-8");
  }
}

export function removePlaintext(root: string, file: string): void {
  const path = join(root, file);
  if (!existsSync(path)) {
    return;
  }

  let content = readFileSync(path, "utf-8");
  const startIdx = content.indexOf(HASH_START_MARKER);
  const endIdx = content.indexOf(HASH_END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + content.slice(endIdx + HASH_END_MARKER.length);
    content = content.replace(/\n{3,}/g, "\n\n").trim() + "\n";
    writeFileSync(path, content, "utf-8");
  }
}
